spring:
  application:
    name: neuroapi
  datasource :
    url : "jdbc:mysql://localhost:3306/db07neuroapp"
    username : root
    password : adminsha256
  jpa:
    database:  mysql
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: "/neuro-doc"
  swagger-ui:
    path : "/swagger-ui-custom.html"

